name: betwinquizapp
description: "A competitive multiplayer quiz application that allows users to challenge friends in real-time, test their knowledge across various categories, and improve their learning through interactive gameplay. Features include live competitions, detailed statistics, and personalized learning paths."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Basic package for iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase related packages
  firebase_core: ^3.8.1 # Core Firebase functionality
  firebase_auth: ^5.3.4 # User authentication operations
  cloud_firestore: ^5.5.1 # Firebase database operations
  google_sign_in: ^5.0.7 # Google account authentication

  # UI/Design packages
  google_fonts: ^6.2.1 # For using Google fonts
  simple_circular_progress_bar: ^1.0.2 # For loading animations
  auto_size_text: ^3.0.0 # For auto-resizing text
  circular_countdown_timer: ^0.2.0 # For quiz countdown timer
  keyboard_avoider: ^0.2.0 # For keyboard management

  # For HTTP requests
  http: ^1.2.2

  # For application splash screen
  flutter_native_splash: ^2.2.10

dev_dependencies:
  # For app icon configuration
  flutter_launcher_icons: ^0.13.1

  # Testing and linting packages
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Application assets
  assets:
    - assets/images/ # General images
    - assets/icons/ # App icons
    - assets/avatars/ # User avatars
    - assets/categories/ # Quiz categories
    - assets/gameSelection/ # Game selection screen assets

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

# Splash screen configuration
flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/icons/logo.png # Splash screen image
  android: true # Android support
  ios: true # iOS support
  fullscreen: true # Fullscreen mode

